from typing import List, Optional
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()


class FileInfo(BaseModel):
    filename: str
    status: Optional[str] = None
    additions: Optional[int] = None
    deletions: Optional[int] = None
    changes: Optional[int] = None
    patch: Optional[str] = None


class ReviewPayload(BaseModel):
    # what kind of event
    kind: str  # "review" or "review_comment"

    # review-level fields
    review_body: Optional[str] = None
    review_state: Optional[str] = None

    # inline comment-level fields
    comment_body: Optional[str] = None
    comment_path: Optional[str] = None
    comment_diff_hunk: Optional[str] = None
    comment_position: Optional[int] = None

    reviewer_login: Optional[str] = None
    pr_number: int
    pr_title: Optional[str] = None
    pr_body: Optional[str] = None
    pr_author_login: Optional[str] = None
    repo_full_name: str
    repo_owner: Optional[str] = None
    repo_name: Optional[str] = None

    files: Optional[List[FileInfo]] = None


class BackendResponse(BaseModel):
    comment: str


@app.post("/analyze-review", response_model=BackendResponse)
async def analyze_review(payload: ReviewPayload):
    """
    Temporary logic that *proves* we got:
      - type of event
      - inline comment / review text
      - list of changed files
    """
    files = payload.files or []
    num_files = len(files)
    first_files = ", ".join(f.filename for f in files[:3])

    if payload.kind == "review":
      source_desc = f"full review with state **{payload.review_state}**"
      text = payload.review_body or ""
    else:
      source_desc = (
          f"inline review comment on `{payload.comment_path}` "
          f"(position {payload.comment_position})"
      )
      text = payload.comment_body or ""

    header = (
        f"I received a **{payload.kind}** ({source_desc}) "
        f"on PR **#{payload.pr_number} – {payload.pr_title}** "
        f"in `{payload.repo_full_name}`.\n\n"
    )

    body_part = (
        f"**Reviewer:** `{payload.reviewer_login}`\n\n"
        f"**Original text:**\n\n> {text.replace('\n', '\n> ')}\n\n"
    )

    files_part = (
        f"I see **{num_files} file(s)** changed in this PR.\n"
    )
    if num_files:
        files_part += f"First up to 3 files:\n" + "\n".join(
            f"- `{f.filename}` (status: {f.status}, +{f.additions}/-{f.deletions})"
            for f in files[:3]
        ) + "\n\n"

    if payload.comment_diff_hunk:
        files_part += (
            "**Diff hunk around this comment:**\n\n"
            "```diff\n"
            + payload.comment_diff_hunk[:600]  # truncate just in case
            + "\n```\n\n"
        )

    footer = "_(auto-generated by ContextWizard backend – proving we see your files and comment context)_"

    return BackendResponse(comment=header + body_part + files_part + footer)
