from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()


class ReviewPayload(BaseModel):
    review_body: str
    review_state: str | None = None
    reviewer_login: str | None = None
    pr_number: int
    pr_title: str | None = None
    pr_body: str | None = None
    pr_author_login: str | None = None
    repo_full_name: str
    repo_owner: str | None = None
    repo_name: str | None = None


class BackendResponse(BaseModel):
    comment: str


@app.post("/analyze-review", response_model=BackendResponse)
async def analyze_review(payload: ReviewPayload):
    """
    Placeholder logic: just echo the review in a nice formatted comment.
    Later you'll replace this with your real LLM/logic.
    """
    # Very simple template – you can customize
    header = f"Thanks for the review on **PR #{payload.pr_number} – {payload.pr_title}**.\n\n"
    reviewer = payload.reviewer_login or "a reviewer"
    review_state = payload.review_state or "commented"

    comment = (
        header
        + f"{reviewer} **{review_state}** this pull request and said:\n\n"
        + f"> {payload.review_body.replace('\n', '\n> ')}\n\n"
        + "_(auto-generated by ContextWizard backend – logic WIP)_"
    )

    return BackendResponse(comment=comment)
